### PR TITLE
refactor, 0.9, docs

### PR DESCRIPTION
**Pull request by atotic**
This is the refactor of google-signin, port to 0.9, and documentation upgrade.

I've renamed the variables as we discussed, reworked initialization so init is called after clientId is set, and auth2 loaded. Getting it all took a while, final puzzler was "how do I do raised buttons in iron"

### CODE REVIEW

**Comment by addyosmani** [comment]
@Zoramite for I/O, we're hoping to have all elements have a 0.9 version available. Would you mind me reviewing/making a call on landing this or do you think you'll have a chance to before mid-next week?

**Comment by Shrugs** [comment]
LGTM :+1:

The clientId in the demo needs to be changed, though; I had the weirdest, hardest-to-debug issues trying to authenticate with that+auth2. The solution was creating my own application/clientId and using that in the demo.

**Comment by atotic** [comment]
@Shrugs by any chance, was it you running on something other than localhost:8080?

**Comment by Shrugs** [comment]
Ah, it may have been running on :8000. I ca re-test. I was able to sign in correctly, though; it didn't give the "javascript origin" issue.

I've made some small changes here: https://github.com/atotic/google-signin/pull/1

**Comment by Shrugs** [comment]
Can confirm that it was the port issue; I wonder why it didn't alert me that "http://localhost:8000 is not a valid javascript origin"?

**Comment by atotic** [comment]
No idea. I spent half a day on 8081 with some obtuse errors. Really annoying that core library does not complain.

**Comment by atotic** [comment]
I am merging it, fixed my nitpick.

**Comment by atotic** [comment]
Good here.

**Comment by atotic** [comment]
PTAL

**Pull request merged**
