### PR TITLE
Updating to use the `gapi.auth2` for sign in.

### PR DESCRIPTION
**Pull request by Zoramite**
Updating the web component to use the updated signin library from google:

see: https://developers.google.com/identity/sign-in/

### CODE REVIEW

**Comment by Zoramite** [comment]
@addyosmani any other things we need to fix here before we merge?

**Comment by addyosmani** [comment]
I'll do one last pass on this in the morning. Can you fix up the merge conflicts please?

**Comment by addyosmani** [comment]
Yay! It's finally in. Great work, @Zoramite! 

giphy

**Comment by addyosmani** [comment]
Follow-up: do you think we need a grace period prior to doing another release, or would you like to go ahead with one that includes these changes?

**Comment by Zoramite** [comment]
I would like to go ahead with one with these changes. I think it would be good to bump the version number up so that people are aware there are breaking changes.

**Comment by addyosmani** [comment]
Great. Assume we're happy to do a 0.3.0 for the release given magnitude of changes?

**Comment by Zoramite** [comment]
That sounds good to me.

**Pull request merged**
